### ISSUE TITLE
`Path must be a string` error on `verb readme`

### ISSUE THREAD

**Issue by vjpr** [verbose/verb-generate-readme#7]
```
> verb readme

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Liftoff.run (/Users/Vaughan/nvm/versions/node/v6.0.0/lib/node_modules/verb-cli/bin/verb.js:133:27)
```

**Comment by vjpr** [comment]
```
  // `verbfile.js`
  if ((hasVerbmd && !hasVerbfile) || !verbfile) {
    verbfile = resolve.sync('verb-default');
    console.log(env)
    env.configBase = path.dirname(env.configBase);
    require(verbfile)(verbInst);
  } else {
    // this is what actually loads up the verbfile
    require(verbfile);
  }
```

Seems to be caused if no `verbfile.js` is present.

**Comment by jonschlinkert** [comment]
Sorry this needs to be up front on the readme (I didn't realize it wasn't until now). To run this generator you need to install the dev branch of verb. I'm working on getting that branch published, hopefully today.

**Comment by vjpr** [comment]
```
npm i -g verbose/verb#dev
npm i -g verb-readme-generator
```

```
Error: Cannot find module 'time-stamp'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Function.getter [as timeStamp] (/Users/Vaughan/nvm/versions/node/v6.0.0/lib/node_modules/verb/node_modules/ansi-colors/node_modules/lazy-cache/index.js:39:29)
    at Function.timestamp (/Users/Vaughan/nvm/versions/node/v6.0.0/lib/node_modules/verb/node_modules/base-runner/node_modules/log-utils/index.js:165:32)
    at Function.utils.timestamp (/Users/Vaughan/nvm/versions/node/v6.0.0/lib/node_modules/verb/node_modules/base-runner/utils.js:80:25)
    at runner (/Users/Vaughan/nvm/versions/node/v6.0.0/lib/node_modules/verb/node_modules/base-runner/index.js:95:9)
    at Object.<anonymous> (/Users/Vaughan/nvm/versions/node/v6.0.0/lib/node_modules/verb/bin/verb.js:21:1)
    at Module._compile (module.js:541:32)
```

**Comment by jonschlinkert** [comment]
that error happens all the time with npm. you need to run `npm i` again, or do `npm cache clean`  then `npm i` again. if that doesn't work, try removing `node_modules` and install again.

**Comment by vjpr** [comment]
I tried all of your suggestions. Still encountering this issue.

lazy-cache@0.2.7 is what is installed and it does not depend on `time-stamp` in its package.json.

**Comment by vjpr** [comment]
I'm finding it difficult to debug...lots of magic going on.

```
define(utils, 'timestamp', function() {
  return '[' + utils.gray(utils.timeStamp('HH:mm:ss')) + ']';
});
```

```
var colors = require('lazy-cache')(require);
```

etc.

**Comment by jonschlinkert** [comment]
> lots of magic going on.

Sorry for the late reply. What kind of magic? The code is pretty transparent. Or do you just mean "dependencies"

**Comment by jonschlinkert** [comment]
closing based on lack of response. I suggest reading the node.js documentation to learn how "the magic" of modules and debugging work.

**Comment by vjpr** [comment]
Sorry I had not had time to reply for a while.

I have tried so many times to get `verb` to work and it just does not work out of the box.

I would rate my expertise in node.js modules at an expert level.

I don't have time to dive into a dependency issue like this.

And when something like this:

`var colors = require('lazy-cache')(require);`

...is causing an error I think it is appropriate for it to be called "magic" without being labelled as an amateur.
